services:

  hbaeumer_erm.parser.plant_uml_entity_parser:
    class: Hbaeumer\ErmBundle\Parser\PlantUmlEntityParser
    arguments:
      - "@doctrine.orm.entity_manager"

  hbaeumer_erm.grapher.encoder:
    class: Hbaeumer\ErmBundle\Grapher\Encoder

  hbaeumer_erm.grapher.client:
    class: GuzzleHttp\Client

  hbaeumer_erm.grapher.plant_uml_grapher:
    class: Hbaeumer\ErmBundle\Grapher\PlantUmlGrapher
    arguments:
      - "@hbaeumer_erm.grapher.client"
      - "@hbaeumer_erm.grapher.encoder"

  Hbaeumer\ErmBundle\Controller\ERMDiagramController:
    arguments:
      - "@hbaeumer_erm.parser.plant_uml_entity_parser"
      - "@hbaeumer_erm.grapher.plant_uml_grapher"
    public: true

  Hbaeumer\ErmBundle\Command\ERMDiagramCommand:
    tags:
      - { name: 'console.command', command: 'doctrine:erm:output' }
    arguments:
      - "@hbaeumer_erm.parser.plant_uml_entity_parser"
      - "@hbaeumer_erm.grapher.plant_uml_grapher"

  Hbaeumer\ErmBundle\DataCollector\HbaeumerErmDataCollector:
    tags:
      -
        name: data_collector
        template: '@HbaumerErm/Toolbar/toolbar.html.twig'
        id: 'hbaeumer_erm'