language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - PHPUNIT_FLAGS="-v"

matrix:
  fast_finish: true
  include:
    # Minimum supported dependencies with the latest and oldest PHP version
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"

      # Test the latest stable release
    - php: 7.1
    - php: 7.2
    - php: 7.3


      # Latest commit to master
    - php: 7.2
      env: STABILITY="dev"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"


install:
  - composer require php-coveralls/php-coveralls
  - composer update --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/phpunit --coverage-clover ./var/clover.xml
